### model
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
trust_remote_code: true
enable_liger_kernel: true
disable_gradient_checkpointing: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json, ds_z3_offload_config.json]

### dataset
dataset: maze_reasoning_filter
template: deepseek3
cutoff_len: 4096
train_on_prompt: true
overwrite_cache: true
preprocessing_num_workers: 32
#packing: true
#neat_packing: true

### output
output_dir: saves/qwen2.5-7b-distil/full/sft
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
